apiVersion: apps/v1
kind: Deployment
metadata:
  name: series-lounge-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: series-lounge-deploy
  template:
    metadata:
      labels:
        app: series-lounge-deploy
    spec:
      containers:
        - name: series-lounge-deploy  # <--- This is the name of the container
          image: sergehall/series-lounge
          resources:
            limits:
              memory: "256Mi" # <--- This is the maximum amount of memory that the container can use
              cpu: "250m"  # <--- This is the maximum amount of CPU that the container can use
          ports:
            - containerPort: 5100 # <--- This is the port that the container is listening on
              protocol: TCP # <--- This is the protocol that the container is listening on
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: series-lounge-deploy
spec:
  type: LoadBalancer
  selector:
    app: series-lounge-deploy
  ports:
    - protocol: TCP
      port: 5100
      targetPort: 5100
